---
- hosts: all
  gather_facts: false
  # tasks:
  #   - name: Create a new Storage Account on Azure portal
  #     shell: "az storage account create
  #             --name {{ storage_account_name }}
  #             --resource-group {{ resource_group_name }}
  #             --access-tier Hot
  #             --kind StorageV2
  #             --location {{ region }}
  #             --sku Standard_RAGRS"
  tasks:
    - name: go to the relative directory
      shell: "cd {{function_name}}"
         
  tasks:
    - name: Deploy function locally
      shell: "func host start --port {{port}}"
  # tasks:
  #   - name: Register env
  #     shell: "echo ${{function_name}}-port"
  #     environment:
  #       {{function_name}}-port: {{port}}
  #     register: {{function_name}}-port
    # - name: Deploy function to Azure function app (using the kudu zip push deployment)
    #   shell: "az functionapp deployment source config-zip \
    #           --name {{ function_app_name }} \
    #           --resource-group {{ resource_group_name }} \
    #           --src {{ zip_file }} \
    #           --build-remote {{ build_remote }} \
    #           --timeout {{ timeout }}"
