---
- hosts: all
  vars:
    name: "function"
  task:
    - name: Get functio url from azure function
      shell: "echo $(az functionapp function show -g {{ resource_group_name}} -n {{function_app_name}} --function-name {{function_name}} --query \"invokeUrlTemplate\")"
      register: azure_function_url
      
    - set_fact:
        azure_function: "{{ (azure_function_url.stdout | from_json)}}"
         
    - name: Unpack connection string dictionary
      debug:
        var: azure_function
    
    - name: register app settings
      command: "az functionapp config appsettings set -g {{ target_resource_group_name }}  -n {{ target_function_app_name }} --settings {{name}}_{{ order }}={{ azure_function }}"
    
#  vars:
#    function_name: "{{ function_name }}"
#    function_app_name: "{{ function_app_name }}"
#    port: "{{ port }}"
#    value: "Values"
#  tasks:
#    # Register env
#    - name: load json
#      include_vars:
#        file: "{{ target_path }}{{ target_function_name }}/local.settings.json"
#        name: imported_var
##
#    - debug:
#        var: imported_var
#
#    - name: add more values
#      vars:
#        function_name_key: "function{{ order }}"
#        function_url: "http://localhost:{{ port }}/api/{{ function_name }}"
#      set_fact:
#        env_var: "{{ imported_var['Values']| combine( {function_name_key: function_url} ) }}"
#
#    - name: together
#      set_fact:
#        imported_var: "{{imported_var| combine ({value: env_var}) }}"
#
##    - name: add more values
##      vars:
##        function_port_key: "function{{ order }}_port"
##      set_fact:
##        env_var2: "{{ imported_var['Values']| combine( {function_port_key: port} ) }}"
##
##
##    - name: together
##      set_fact:
##        imported_var: "{{imported_var| combine ({value: env_var2}) }}"
##
##    - debug:
##        var: imported_var
##
#    - name: write var to file
#      copy:
#        content: "{{ imported_var | to_nice_json }}"
#        dest: "{{ target_path }}{{ target_function_name }}/local.settings.json"
#
#    #   vars:
#    #     ansible_python_interpreter: /usr/local/bin/python
#    #   shell: export "{{ function_name}}"="{{ port }}"
#    #   # environment:
#    #   #   function_name: "{{ port }}"
#    #   register: shellout
#
#    # - debug:
#    #     var: shellout.stdout
